# Generated by Django 5.2.10 on 2026-02-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='after_plan1',
            field=models.ImageField(blank=True, null=True, upload_to='generated/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='after_plan2',
            field=models.ImageField(blank=True, null=True, upload_to='generated/'),
        ),
    ]
