# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step4.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/bg_step4.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(254, 56, 515, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_2.setObjectName("label_2")
        self.pushButton_qrcode = QtWidgets.QPushButton(Form)
        self.pushButton_qrcode.setGeometry(QtCore.QRect(305, 176, 171, 248))
        self.pushButton_qrcode.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_qrcode_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #FFFFFF;                /* 文字顏色 */\n"
"        font-size: 32pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_qrcode_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 32pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_qrcode.setText("")
        self.pushButton_qrcode.setIconSize(QtCore.QSize(171, 248))
        self.pushButton_qrcode.setFlat(True)
        self.pushButton_qrcode.setObjectName("pushButton_qrcode")
        self.pushButton_card = QtWidgets.QPushButton(Form)
        self.pushButton_card.setGeometry(QtCore.QRect(548, 176, 171, 248))
        self.pushButton_card.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_card_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #FFFFFF;                /* 文字顏色 */\n"
"        font-size: 32px;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_card_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 32px;             /* 字體大小 */\n"
"    }")
        self.pushButton_card.setText("")
        self.pushButton_card.setIconSize(QtCore.QSize(171, 248))
        self.pushButton_card.setFlat(True)
        self.pushButton_card.setObjectName("pushButton_card")
        self.pushButton_previous = QtWidgets.QPushButton(Form)
        self.pushButton_previous.setGeometry(QtCore.QRect(270, 485, 196, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_previous.setFont(font)
        self.pushButton_previous.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_gr_196x70_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #E9E9E9;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_gr_196x70_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_previous.setIconSize(QtCore.QSize(196, 70))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(558, 485, 196, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_196x70_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #FFFFFF;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_196x70_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_exit.setIconSize(QtCore.QSize(196, 70))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Choose one to start charging"))
        self.pushButton_previous.setText(_translate("Form", "Previous"))
        self.pushButton_exit.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
