# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/bg_step3.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 56, 764, 92))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 18pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(304, 148, 415, 317))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("image/fig_02.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.pushButton_previous = QtWidgets.QPushButton(Form)
        self.pushButton_previous.setGeometry(QtCore.QRect(270, 485, 196, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_previous.setFont(font)
        self.pushButton_previous.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_gr_196x70_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #E9E9E9;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_gr_196x70_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_previous.setIconSize(QtCore.QSize(196, 70))
        self.pushButton_previous.setFlat(True)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_next = QtWidgets.QPushButton(Form)
        self.pushButton_next.setGeometry(QtCore.QRect(558, 485, 196, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_196x70_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #FFFFFF;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_196x70_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_next.setIconSize(QtCore.QSize(196, 70))
        self.pushButton_next.setFlat(True)
        self.pushButton_next.setObjectName("pushButton_next")
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_previous.raise_()
        self.pushButton_next.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Remove the charging gun and insert it into\n"
"the vehicle’s charging interface"))
        self.pushButton_previous.setText(_translate("Form", "Previous"))
        self.pushButton_next.setText(_translate("Form", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
