# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step7_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/bg_step7.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(361, 56, 301, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 24pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_2.setObjectName("label_2")
        self.battery = QtWidgets.QLabel(Form)
        self.battery.setGeometry(QtCore.QRect(120, 150, 108, 203))
        self.battery.setText("")
        self.battery.setPixmap(QtGui.QPixmap("image/battery-0.png"))
        self.battery.setObjectName("battery")
        self.battery_num = QtWidgets.QLabel(Form)
        self.battery_num.setGeometry(QtCore.QRect(230, 180, 211, 147))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(83)
        self.battery_num.setFont(font)
        self.battery_num.setStyleSheet("QLabel {\n"
"        color: rgb(255, 120, 0);                /* 文字顏色 */\n"
"        font-size: 83pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.battery_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.battery_num.setObjectName("battery_num")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(516, 154, 54, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(667, 202, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(735, 154, 105, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(797, 202, 12, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(875, 202, 31, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(516, 250, 54, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(667, 297, 11, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(735, 250, 83, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(880, 297, 20, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(516, 345, 48, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(657, 392, 23, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(735, 345, 103, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(871, 392, 31, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 9pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_15.setObjectName("label_15")
        self.voltage = QtWidgets.QLabel(Form)
        self.voltage.setGeometry(QtCore.QRect(546, 178, 103, 47))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.voltage.setFont(font)
        self.voltage.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.voltage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voltage.setObjectName("voltage")
        self.hour = QtWidgets.QLabel(Form)
        self.hour.setGeometry(QtCore.QRect(766, 178, 23, 47))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.hour.setFont(font)
        self.hour.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.hour.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hour.setObjectName("hour")
        self.min = QtWidgets.QLabel(Form)
        self.min.setGeometry(QtCore.QRect(819, 178, 46, 47))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.min.setFont(font)
        self.min.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.min.setObjectName("min")
        self.kg = QtWidgets.QLabel(Form)
        self.kg.setGeometry(QtCore.QRect(754, 273, 111, 47))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.kg.setFont(font)
        self.kg.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.kg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kg.setObjectName("kg")
        self.power = QtWidgets.QLabel(Form)
        self.power.setGeometry(QtCore.QRect(528, 368, 121, 47))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.power.setFont(font)
        self.power.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.power.setObjectName("power")
        self.amp = QtWidgets.QLabel(Form)
        self.amp.setGeometry(QtCore.QRect(538, 273, 111, 47))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.amp.setFont(font)
        self.amp.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.amp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amp.setObjectName("amp")
        self.nt = QtWidgets.QLabel(Form)
        self.nt.setGeometry(QtCore.QRect(744, 368, 121, 47))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.nt.setFont(font)
        self.nt.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 26pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.nt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nt.setObjectName("nt")
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(387, 467, 250, 88))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_250x88_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #FFFFFF;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_250x88_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_stop.setIconSize(QtCore.QSize(250, 88))
        self.pushButton_stop.setFlat(True)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(504, 148, 185, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("image/bg_battery_inf.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(440, 240, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(42)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"        color: #FF7800;                /* 文字顏色 */\n"
"        font-size: 42pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(504, 338, 185, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("image/bg_battery_inf.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(724, 338, 185, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("image/bg_battery_inf.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(504, 243, 185, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("image/bg_battery_inf.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(724, 148, 185, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("image/bg_battery_inf.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(724, 243, 185, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("image/bg_battery_inf.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label.raise_()
        self.label_2.raise_()
        self.battery.raise_()
        self.battery_num.raise_()
        self.pushButton_stop.raise_()
        self.label_16.raise_()
        self.label_3.raise_()
        self.voltage.raise_()
        self.label_4.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_8.raise_()
        self.amp.raise_()
        self.label_9.raise_()
        self.label_12.raise_()
        self.power.raise_()
        self.label_13.raise_()
        self.label_5.raise_()
        self.hour.raise_()
        self.label_6.raise_()
        self.min.raise_()
        self.label_7.raise_()
        self.label_10.raise_()
        self.kg.raise_()
        self.label_11.raise_()
        self.label_14.raise_()
        self.nt.raise_()
        self.label_15.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Battery Charging"))
        self.battery_num.setText(_translate("Form", "0"))
        self.label_3.setText(_translate("Form", "Voltage"))
        self.label_4.setText(_translate("Form", "V"))
        self.label_5.setText(_translate("Form", "Charging Time"))
        self.label_6.setText(_translate("Form", "H"))
        self.label_7.setText(_translate("Form", " Min"))
        self.label_8.setText(_translate("Form", "Current"))
        self.label_9.setText(_translate("Form", "A"))
        self.label_10.setText(_translate("Form", "CO2 Saved"))
        self.label_11.setText(_translate("Form", "Kg"))
        self.label_12.setText(_translate("Form", "Power"))
        self.label_13.setText(_translate("Form", "Kw"))
        self.label_14.setText(_translate("Form", "Charging Cost"))
        self.label_15.setText(_translate("Form", "NT$"))
        self.voltage.setText(_translate("Form", "220.9"))
        self.hour.setText(_translate("Form", "0"))
        self.min.setText(_translate("Form", "00"))
        self.kg.setText(_translate("Form", "0.00"))
        self.power.setText(_translate("Form", "0.0"))
        self.amp.setText(_translate("Form", "0"))
        self.nt.setText(_translate("Form", "0"))
        self.pushButton_stop.setText(_translate("Form", "Stop"))
        self.label_17.setText(_translate("Form", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
