# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step8.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/bg_step8.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(391, 56, 241, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 24pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(252, 125, 190, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"        color: rgb(189, 189, 189);                /* 文字顏色 */\n"
"        font-size: 13pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(252, 254, 142, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"        color: rgb(189, 189, 189);                /* 文字顏色 */\n"
"        font-size: 13pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(252, 297, 128, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"        color: rgb(189, 189, 189);                /* 文字顏色 */\n"
"        font-size: 13pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(252, 392, 152, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"        color: rgb(189, 189, 189);                /* 文字顏色 */\n"
"        font-size: 13pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_6.setObjectName("label_6")
        self.label_datetime = QtWidgets.QLabel(Form)
        self.label_datetime.setEnabled(True)
        self.label_datetime.setGeometry(QtCore.QRect(361, 155, 401, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_datetime.setFont(font)
        self.label_datetime.setStyleSheet("QLabel {\n"
"        color: rgb(255, 120, 0);                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_datetime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_datetime.setObjectName("label_datetime")
        self.label_power = QtWidgets.QLabel(Form)
        self.label_power.setGeometry(QtCore.QRect(520, 247, 241, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_power.setFont(font)
        self.label_power.setStyleSheet("QLabel {\n"
"        color: rgb(255, 120, 0);                /* 文字顏色 */\n"
"        font-size:16pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_power.setObjectName("label_power")
        self.label_creditcard = QtWidgets.QLabel(Form)
        self.label_creditcard.setGeometry(QtCore.QRect(502, 385, 261, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_creditcard.setFont(font)
        self.label_creditcard.setStyleSheet("QLabel {\n"
"        color: rgb(255, 120, 0);                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_creditcard.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_creditcard.setObjectName("label_creditcard")
        self.label_nt = QtWidgets.QLabel(Form)
        self.label_nt.setGeometry(QtCore.QRect(510, 289, 251, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_nt.setFont(font)
        self.label_nt.setStyleSheet("QLabel {\n"
"        color: rgb(255, 120, 0);                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_nt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nt.setObjectName("label_nt")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(252, 216, 175, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(252, 354, 229, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size:16pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_12.setObjectName("label_12")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(252, 196, 520, 3))
        self.line.setStyleSheet("color:#1E77D7")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(252, 341, 520, 3))
        self.line_2.setStyleSheet("color:#1E77D7")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_ok = QtWidgets.QPushButton(Form)
        self.pushButton_ok.setGeometry(QtCore.QRect(387, 467, 250, 88))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_250x88_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_250x88_act.png\") 0 0 0 0 stretch stretch;\n"
"       color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 20pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_ok.setIconSize(QtCore.QSize(250, 88))
        self.pushButton_ok.setFlat(True)
        self.pushButton_ok.setObjectName("pushButton_ok")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Billing Details"))
        self.label_3.setText(_translate("Form", "Charging Date / Time"))
        self.label_4.setText(_translate("Form", "Charging power"))
        self.label_5.setText(_translate("Form", "Charging Cost"))
        self.label_6.setText(_translate("Form", "Payment Method"))
        self.label_datetime.setText(_translate("Form", "2025/05/31 02:00~2025/05/31 02:15"))
        self.label_power.setText(_translate("Form", "7.16000 Kw"))
        self.label_creditcard.setText(_translate("Form", "Credit Card (**111)"))
        self.label_nt.setText(_translate("Form", "53100 NT$"))
        self.label_11.setText(_translate("Form", "Cost Calculation"))
        self.label_12.setText(_translate("Form", "Payment Information"))
        self.pushButton_ok.setText(_translate("Form", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
