# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/bg_step2.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(218, 56, 586, 92))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("QLabel {\n"
"        color: white;                /* 文字顏色 */\n"
"        font-size: 18pt;             /* 字體大小 */\n"
"        font-family: \"Arial\";\n"
"    }\n"
"  ")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.pushButton_ccs1 = QtWidgets.QPushButton(Form)
        self.pushButton_ccs1.setGeometry(QtCore.QRect(305, 162, 171, 290))
        self.pushButton_ccs1.setAutoFillBackground(False)
        self.pushButton_ccs1.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(\"image/btn_ccs1_def.png\") 0 0 0 0 stretch stretch;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        border-image: url(\"image/btn_ccs1_act.png\") 0 0 0 0 stretch stretch;\n"
"    }")
        self.pushButton_ccs1.setText("")
        self.pushButton_ccs1.setIconSize(QtCore.QSize(171, 307))
        self.pushButton_ccs1.setFlat(True)
        self.pushButton_ccs1.setObjectName("pushButton_ccs1")
        self.pushButton_ccs2 = QtWidgets.QPushButton(Form)
        self.pushButton_ccs2.setGeometry(QtCore.QRect(548, 162, 171, 290))
        self.pushButton_ccs2.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(\"image/btn_ccs2_def.png\") 0 0 0 0 stretch stretch;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        border-image: url(\"image/btn_ccs2_act.png\") 0 0 0 0 stretch stretch;\n"
"    }")
        self.pushButton_ccs2.setText("")
        self.pushButton_ccs2.setIconSize(QtCore.QSize(171, 307))
        self.pushButton_ccs2.setFlat(True)
        self.pushButton_ccs2.setObjectName("pushButton_ccs2")
        self.pushButton_previous = QtWidgets.QPushButton(Form)
        self.pushButton_previous.setGeometry(QtCore.QRect(270, 485, 196, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_previous.setFont(font)
        self.pushButton_previous.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_gr_196x70_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #E9E9E9;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_gr_196x70_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_previous.setIconSize(QtCore.QSize(196, 70))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(558, 485, 196, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"        border-image: url(\"image/btn_196x70_def.png\") 0 0 0 0 stretch stretch;\n"
"        color: #FFFFFF;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-image: url(\"image/btn_196x70_act.png\") 0 0 0 0 stretch stretch;\n"
"color: #FFFF00;                /* 文字顏色 */\n"
"        font-size: 16pt;             /* 字體大小 */\n"
"    }")
        self.pushButton_exit.setIconSize(QtCore.QSize(196, 70))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Choose the charging interface is\n"
"compatible with the vehicle"))
        self.pushButton_previous.setText(_translate("Form", "Previous"))
        self.pushButton_exit.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
